### ISSUE TITLE
Handling homepage for multi lang

### ISSUE THREAD

**Issue by arjunadotfusion** [agility/gatsby-source-agilitycms#6] opened 2020-05-05 20:20 UTC
Home page redirections happen on multi lang sites. Ideally the '/home' node should have a redirect that is language sensitive.

**Comment by jamesvidler** [comment] 2020-05-05 20:23
@arjunadotfusion what would be the intended behavior for a multi-language site with an incoming request to `/home` or `/`, would you want that to redirect to the default language i.e. `/en-us/`?

**Comment by arjunadotfusion** [comment] 2020-05-05 20:36
@jamesvidler - ideally it would handle intelligently so the first node would default to the path provided and create the redirect no?

**Comment by arjunadotfusion** [comment] 2020-05-05 20:43
Ideally with a config like this :

```
languages: [
          {
            // The name of the language code
            name: "French",
            // The actual language code set in Agility CMS
            code: "fr", 
            // The name to be used in the URL path that represents the current language
            path: "/fr"     
          },
          {
            // The name of the language code
            name: "English",
            // The actual language code set in Agility CMS
            code: "en-us", 
            // The name to be used in the URL path that represents the current language
            path: ""
          }
        ],
```
The french home (`/fr/home`) should redirect to `/fr` and (`/en/home`) should redirect to the base url

**Comment by jamesvidler** [comment] 2020-05-05 21:22
The way we had intended for it to work in a multi-lang site would be the following:

1. A request to `/` would redirect to `/en/` (path param for English)
2. A request to `/fr/home` would redirect to `/fr/` (path param for French)

That way, every single page always has a language code in it. Does it currently work that way and you want to change it to always stay on '/' for the English language only?

**Comment by arjunadotfusion** [comment] 2020-05-05 21:57
Currently home page logic only kicks in for the last language in the config and it respects the path params in the config. 

Unfortunately, currently redirects hit all `/home` nodes, or rather first child nodes of the sitemap and redirect to `/`.

i think the change has to be in the [this function](https://github.com/agility/gatsby-source-agilitycms/blob/8cf89ba986215ec0d9dea228d5860b711d92bad4/gatsby-node.js#L375) where it handles it for base as well as for the language path prop.

**Comment by jamesvidler** [comment] 2020-05-06 15:10
@arjunadotfusion we just committed fixes for multi-language support. Here is how it works:

1. A request to / would redirect to /en/ (the default path for the first language)
2. A request to /en/home would redirect to /en/
3. A request to /fr/home would redirect to /fr/ 

Can you take a look at the latest version **1.4.0** and see if this resolves the issue you are seeing?

**Closed** 2020-05-11 21:06 UTC
